name: Deploy Storybook

on:
  push:
    branches:
      - master  # Trigger on push to 'main' branch

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]  # Node.js version to use

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Yarn 4.6.0
        run: |
          corepack enable
          corepack prepare yarn@4.6.0 --activate

      - name: Install dependencies
        run: yarn install --frozen-lockfile  # Ensures no changes to yarn.lock

      - name: Build Storybook
        run: yarn build-storybook

      - name: Deploy Storybook to GitHub Pages
        run: |
          git remote set-url origin https://git:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git config --global user.name "github-actions-bot"
          git config --global user.email "support+actions@github.com"
          yarn deploy-storybook
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
