name: Deploy Storybook

on:
  push:
    branches:
      - master  # Trigger on push to 'main' branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest

    steps:
      # Manual Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Set up Node
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      #👇 Add Storybook build and deploy to GitHub Pages as a step in the workflow
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: yarn install # default: npm ci
          build_command: yarn build-storybook # default: npm run build-storybook
          path: storybook-static # default: dist/storybook
          checkout: false # default: true
